#!/usr/bin/python3
from pymongo import MongoClient, errors
from bson.json_util import dumps
import os
import json

MONGOPASS = os.getenv('MONGOPASS')
uri = "mongodb+srv://cluster0.pnxzwgz.mongodb.net/fpt9nh"
client = MongoClient(uri, username='nmagee', password=MONGOPASS, connectTimeoutMS=200, retryWrites=True)
db = client["fpt9nh"]
collection = db["movie_stars"]

db.movie_stars.insertOne({"name":"Jessica Chastain","Movies":["Interstellar","Molly's Game","The Help"]})
db.movie_stars.insertOne({"name":"Hugh Grant","Movies":["Notting Hill","Love Actually","4 Wedding and A Funeral"]})
db.movie_stars.insertOne({"name":"Angelina Jolie","Movies":["Mr. and Mrs. Smith","Girl, Interrupted"]})
db.movie_stars.insertOne({"name":"Kevin Hart","Movies":["Lift","Ride Along","The Upside"]})
db.movie_stars.insertOne({"name":"Steve Carrell","Movies":["Despicable Me","Crazy, Stupid Love"]})

three_docs = collection.find().limit(3) # find 3 docs in the collection
# list the 3 docs
for doc in three_docs:
    print(doc)

# unable to connect to mongodb, so the db will not appear on mongo